### ISSUE TITLE
Home: To-do board

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project--vitamed#4]
## Value Statement

As a user, I want to see, add and delete things I should keep in mind, e.g. calling a doctor, getting a new prescription etc.

## Description

![Bildschirmfoto 2022-01-05 um 15 56 57](https://user-images.githubusercontent.com/93935781/148238597-95830546-bd71-4095-9c51-97dfd4c85d8a.png)

## Complexitiy

M

## Acceptance Criteria

- The user can see the current to-do's
- The user can edit and delete a current to-do
- The user can add a new to-do and submit the new input

## Tasks

- [x] Create "to-do" component
- [x] Import component
- [x] Build component with to-do-list
- [x] Add edit and delete function to the component
- [x] Add buttons with submit function
- [x] Add input field for new to-do
- [x] Add styling
